DROP TABLE IF EXISTS USER;

CREATE TABLE USER(
id INT AUTO_INCREMENT PRIMARY KEY,
username NVARCHAR(50) NOT NULL,
password NVARCHAR(300) NOT NULL,
role NVARCHAR(50) NOT NULL
);
INSERT INTO USER(username,password,role) VALUES
('khang','$2a$10$uFAVHkhq5M1No03U9J0btexq0.ACgo3HhAl0WY3vFYAZ.kwImGmwe','ROLE_ADMIN'),
('user','$2a$10$yKNKIb7nin/RWD1.0wWmsuP0FmbR6H4SkYqKO0STcSOgP8In90/oW','ROLE_USER')
;